// Headed, watchable UI walkthrough of the current build (Row 2 strip + sticky footer).
import { chromium } from "@playwright/test";
const BASE = "http://127.0.0.1:7001";
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const seed = async (page, vendor, theme) => {
  await page.goto(BASE + "/", { waitUntil:"domcontentloaded", timeout:25000 });
  await page.evaluate(({vendor,theme}) => {
    try { localStorage.clear(); } catch {}
    localStorage.setItem("pulseplay:bi-vendor", vendor);
    localStorage.setItem("pulseplay:active-ai-profile","default");
    localStorage.setItem("pulseplay:default-landing-surface","ai-insights");
    const k="pulseplay:visual-settings:genieSettings";
    const ex=JSON.parse(localStorage.getItem(k)||"{}");
    ex.assistantProfile="default"; ex.connectionMode="proxy"; ex.apiBaseUrl=location.origin+"/api";
    if (theme==="dark"){ ex.darkMode=true; localStorage.setItem("pulseplay:theme-mode","dark"); }
    if (theme==="aaa") ex.themeName="accessibility-aaa";
    localStorage.setItem(k, JSON.stringify(ex));
  }, {vendor,theme});
};
const browser = await chromium.launch({ headless:false, slowMo:230, args:["--window-size=1480,940","--window-position=30,30"] });
const ctx = await browser.newContext({ viewport:{ width:1440, height:880 } });
const page = await ctx.newPage();

console.log("① AI Insights — Row 2 control strip (nav | Adjust | 🔄 ⚙ ⋮ + agent status) + sticky footer at bottom");
await seed(page,"powerbi",null);
await page.goto(`${BASE}/?surface=ai-insights`, { waitUntil:"domcontentloaded", timeout:25000 });
await page.locator(".gn-header-run-state .gn-insights-progress-wrap--header").waitFor({ state:"visible", timeout:45000 }).catch(()=>{});
await sleep(3500);

console.log("② ⋮ menu — Data Portability only (Copy md / Copy HTML / Print)");
await page.locator("[data-testid='gn-insights-overflow-trigger']").first().click().catch(()=>{});
await sleep(3000);
await page.keyboard.press("Escape").catch(()=>{});

console.log("③ Let it finish — agent status hides; footer 'Generated by PulsePlay · v1.0.4 Enterprise' stays");
const dl=Date.now()+150000;
while(Date.now()<dl){ const busy=await page.locator(".gn-header-run-state .gn-insights-progress-wrap--header").isVisible().catch(()=>false); const secs=await page.locator('[data-section]:not(.gn-insights-section--placeholder)').count(); if(!busy&&secs>=2)break; await sleep(2000);}
await sleep(2500);

console.log("④ Composer Bridge — sparkle seeds Ask Pulse");
const ask = page.locator(".gn-insights-provenance-action--ask").first();
if (await ask.isVisible().catch(()=>false)) { await ask.click().catch(()=>{}); await sleep(3000); }

console.log("⑤ Dark theme — footer goes #0F172A / #94A3B8");
await seed(page,"powerbi","dark");
await page.goto(`${BASE}/?surface=ai-insights`, { waitUntil:"domcontentloaded", timeout:25000 });
await sleep(4000);

console.log("⑥ Accessibility-AAA — black / 2px white / yellow (footer too)");
await seed(page,"powerbi","aaa");
await page.goto(`${BASE}/?surface=ai-insights`, { waitUntil:"domcontentloaded", timeout:25000 });
await sleep(4000);

console.log("⑦ Dashboard (native) — collapsed ⚙ Context pill");
await seed(page,"native",null);
await page.goto(`${BASE}/?surface=dashboard`, { waitUntil:"domcontentloaded", timeout:25000 });
await sleep(3000);

console.log("✓ done — closing in 4s");
await sleep(4000);
await browser.close();
