// playground/src/settings/groups/SetupGroup.tsx
//
// Quick Setup — single-page canvas that gets PulsePlay 80% configured
// without the author having to navigate between BI, AI, Preferences,
// System, and Advanced. Inline pickers + live test buttons + rich help
// tooltips. The deeper per-area pages remain available for fine-tuning.

import { useCallback, useEffect, useMemo, useState } from "react";
import { navigateToSettings } from "../settingsRoute";
import { useSettings } from "../settingsStore";
import { useEmbedConfig } from "../embedConfigStore";
import { getSetupReadiness, isNativeBiVendor } from "../setupReadiness";
import { resolveBiSurfaceVendor, type BiSurfaceMode } from "../biSurfaceMode";
import { listVendors } from "../../biPanel/registry";
import {
    FieldCard,
    FieldRow,
    StatusBadge,
    TestButton,
    type TestResult,
} from "../primitives";
import "../primitives/primitives.css";

const VENDOR_HELP: Record<string, React.ReactNode> = {
    "powerbi": (
        <>
            <strong>Microsoft Power BI.</strong> Embed reports via the official <code>powerbi-client</code> SDK. Requires an embed URL, workspace ID, and report ID. Authentication can be SSO (AAD), service principal, or a paste-in secure embed link.
        </>
    ),
    "databricks-aibi": (
        <>
            <strong>Databricks AI/BI dashboards.</strong> Embed via the <code>@databricks/aibi-client</code> token flow or a basic iframe. SDK mode needs a workspace URL, dashboard ID, and workspace ID; basic mode just needs an embed URL.
        </>
    ),
    "databricks-genie": (
        <>
            <strong>Databricks Genie Space.</strong> Paste the iframe HTML generated by <em>Share → Embed space</em> in the Genie UI. No SDK needed.
        </>
    ),
    "native": (
        <>
            <strong>Native result canvas.</strong> PulsePlay renders AI query results directly in the BI pane. No external BI embed URL or vendor credentials are required.
        </>
    ),
    "tableau": <><strong>Tableau.</strong> View URL via Tableau Embedding API v3. Bring the public/server view URL.</>,
    "qlik": <><strong>Qlik Sense.</strong> Apps/sheets via qlik-embed web components or the Single Integration iframe API.</>,
    "looker": <><strong>Looker.</strong> Dashboards / Looks via signed-URL iframe + JS embed events.</>,
    "generic-iframe": <><strong>Generic iframe.</strong> Any URL — escape hatch for vendors PulsePlay doesn't yet have an SDK adapter for. Works today; no credentials needed.</>,
};

interface SetupProfileMetadata {
    name: string;
    displayName?: string;
    dataDomain?: string;
    description?: string;
    spaceId?: string;
    type?: string;
    spaces?: string[];
}

interface SetupPackOption {
    name: string;
    displayName?: string;
}

export function SetupGroup(): React.ReactElement {
    const {
        biVendor, activeAiProfile, packSelection,
        biSurfaceMode,
        allowlist, allowlistError, allowlistLoading, orphans,
        setBiVendor, setBiSurfaceMode, setActiveAiProfile, setPackSelection,
    } = useSettings();
    const { embedConfig, setEmbedConfig } = useEmbedConfig();
    const vendors = useMemo(() => listVendors(), []);
    const allowedBiVendors = useMemo(() => {
        if (!allowlist?.biProviders?.length) return vendors;
        const set = new Set(allowlist.biProviders);
        return vendors.filter(v => set.has(v.vendor));
    }, [vendors, allowlist]);
    const hasVendorEmbedConfig = !!embedConfig && Object.keys(embedConfig).length > 0;
    const surfaceResolution = resolveBiSurfaceVendor({
        mode: biSurfaceMode,
        requestedVendor: biVendor,
        hasVendorEmbedConfig,
        visibleVendors: allowedBiVendors,
    });
    const runtimeBiVendor = surfaceResolution.runtimeVendor;
    const readiness = getSetupReadiness({ biVendor: runtimeBiVendor, embedConfig, activeAiProfile });

    const aiProfiles = allowlist?.aiProfiles ?? [];
    const packs = allowlist?.packs ?? [];
    const allowlistConfigured = allowlist?.configured === true;

    const [liveProfiles, setLiveProfiles] = useState<SetupProfileMetadata[]>([]);
    const [profilesLoading, setProfilesLoading] = useState(true);
    const [livePacks, setLivePacks] = useState<SetupPackOption[]>([]);
    const [packsLoading, setPacksLoading] = useState(true);

    useEffect(() => {
        let cancelled = false;
        (async () => {
            try {
                const res = await fetch("/api/assistant/profiles", { headers: { Accept: "application/json" } });
                if (!res.ok) throw new Error(`HTTP ${res.status}`);
                const data = await res.json();
                const list = normalizeProfilesPayload(data);
                if (!cancelled) setLiveProfiles(list);
            } catch {
                if (!cancelled) setLiveProfiles([]);
            } finally {
                if (!cancelled) setProfilesLoading(false);
            }
        })();
        return () => { cancelled = true; };
    }, []);

    useEffect(() => {
        let cancelled = false;
        (async () => {
            try {
                const res = await fetch("/api/assistant/knowledge/packs", { headers: { Accept: "application/json" } });
                if (!res.ok) throw new Error(`HTTP ${res.status}`);
                const data = await res.json();
                const list = normalizePacksPayload(data);
                if (!cancelled) setLivePacks(list);
            } catch {
                if (!cancelled) setLivePacks([]);
            } finally {
                if (!cancelled) setPacksLoading(false);
            }
        })();
        return () => { cancelled = true; };
    }, []);

    const visibleProfiles = useMemo<SetupProfileMetadata[]>(() => {
        if (allowlistConfigured) {
            if (aiProfiles.length === 0) return [];
            const byName = new Map(liveProfiles.map(p => [p.name, p]));
            return aiProfiles.map(name => byName.get(name) ?? { name });
        }
        if (liveProfiles.length > 0) return liveProfiles;
        return aiProfiles.map(name => ({ name }));
    }, [allowlistConfigured, aiProfiles, liveProfiles]);

    const visiblePacks = useMemo<SetupPackOption[]>(() => {
        if (allowlistConfigured) {
            if (packs.length === 0) return [];
            const byName = new Map(livePacks.map(p => [p.name, p]));
            return packs.map(name => byName.get(name) ?? { name });
        }
        if (livePacks.length > 0) return livePacks;
        return packs.map(name => ({ name }));
    }, [allowlistConfigured, packs, livePacks]);

    const activeProfileMeta = useMemo(
        () => visibleProfiles.find(p => p.name === activeAiProfile) ?? liveProfiles.find(p => p.name === activeAiProfile) ?? null,
        [visibleProfiles, liveProfiles, activeAiProfile],
    );

    const activeProfileDocs = useMemo(
        () => docsForProfile(activeProfileMeta, activeAiProfile),
        [activeProfileMeta, activeAiProfile],
    );

    // ── Live probe handlers ────────────────────────────────────────
    const probeProxy = useCallback<() => Promise<TestResult>>(async () => {
        const started = performance.now();
        try {
            const res = await fetch("/api/health", { headers: { Accept: "application/json" } });
            const elapsed = Math.round(performance.now() - started);
            if (!res.ok) {
                return { tone: "missing", label: "Proxy unreachable", detail: `HTTP ${res.status} · ${elapsed} ms` };
            }
            const data = await res.json();
            const profileCount = Array.isArray(data?.profiles) ? data.profiles.length : 0;
            return {
                tone: "ok",
                label: "Proxy online",
                detail: `${profileCount} profile${profileCount === 1 ? "" : "s"} · ${elapsed} ms`,
            };
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return { tone: "missing", label: "Proxy offline", detail: msg.slice(0, 100) };
        }
    }, []);

    const probeAiProfile = useCallback<() => Promise<TestResult>>(async () => {
        if (!activeAiProfile) {
            return { tone: "warn", label: "No profile selected", detail: "Pick a profile above first" };
        }
        try {
            const res = await fetch(`/api/assistant/profiles?assistantProfile=${encodeURIComponent(activeAiProfile)}`, {
                headers: { Accept: "application/json" },
            });
            if (!res.ok) {
                return { tone: "missing", label: "Profile probe failed", detail: `HTTP ${res.status}` };
            }
            const data = await res.json();
            const profile = normalizeProfilesPayload(data).find(p => p.name === activeAiProfile) ?? null;
            if (!profile) {
                return { tone: "warn", label: "Profile not registered", detail: `'${activeAiProfile}' missing on proxy` };
            }
            const detail = profile.type ? `${profile.type}${profile.spaceId ? " · space " + profile.spaceId.slice(0, 8) + "…" : ""}` : "registered";
            return { tone: "ok", label: "Profile reachable", detail };
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return { tone: "missing", label: "Probe failed", detail: msg.slice(0, 100) };
        }
    }, [activeAiProfile]);

    // ── Inline embed URL editor (the most common config path) ──────
    const [embedUrl, setEmbedUrl] = useState<string>(() => readEmbedUrl(embedConfig));
    const [embedError, setEmbedError] = useState<string | null>(null);
    const [embedSavedAt, setEmbedSavedAt] = useState<number | null>(null);

    const handleApplyEmbed = useCallback(() => {
        setEmbedError(null);
        const url = embedUrl.trim();
        if (!url) {
            setEmbedError("Enter the embed URL or iframe HTML before applying.");
            return;
        }
        try {
            const cfg = buildEmbedConfig(biVendor, url);
            if (!cfg) {
                setEmbedError(`PulsePlay can't auto-build a config for '${biVendor}' from a single URL. Use the BI group → Embed for the full form.`);
                return;
            }
            setEmbedConfig(cfg);
            setEmbedSavedAt(Date.now());
        } catch (err) {
            setEmbedError(err instanceof Error ? err.message : String(err));
        }
    }, [biVendor, embedUrl, setEmbedConfig]);

    const handleClearEmbed = useCallback(() => {
        setEmbedConfig(null);
        setEmbedUrl("");
        setEmbedError(null);
        setEmbedSavedAt(null);
    }, [setEmbedConfig]);

    // ── Card status tones ──────────────────────────────────────────
    const authorNativeBi = isNativeBiVendor(biVendor);
    const runtimeNativeBi = isNativeBiVendor(runtimeBiVendor);
    const biStatus = runtimeBiVendor && readiness.hasEmbedConfig ? "ok" : !runtimeBiVendor ? "missing" : "warn";
    const aiStatus = activeAiProfile ? "ok" : "missing";
    const packStatus = packSelection ? "ok" : "warn";

    return (
        <section aria-labelledby="settings-setup-title" className="pp-setup">
            <header className="pp-setup__head">
                <div>
                    <h2 id="settings-setup-title" className="pp-setup__title">
                        Setup
                    </h2>
                    <p className="pp-setup__subtitle">
                        Three short steps to get PulsePlay running. Each card configures one axis inline; deeper tuning lives in the BI, AI, and Preferences pages.
                    </p>
                </div>
                <div className="pp-setup__readiness">
                    <StatusBadge
                        tone={readiness.ready ? "ok" : "warn"}
                        label={readiness.ready ? "Ready" : "Setup needed"}
                        detail={readiness.ready ? "BI + AI" : `Missing: ${readiness.missing.join(", ")}`}
                    />
                </div>
            </header>

            {allowlistError && (
                <div className="pp-setup__alert" role="alert">
                    <strong>Governance allowlist unreachable.</strong> {allowlistError}
                    {" · "}
                    <button type="button" className="pp-setup__alert-action" onClick={() => navigateToSettings("system", "proxy-status")}>
                        Check proxy →
                    </button>
                </div>
            )}

            {orphans.length > 0 && (
                <div className="pp-setup__alert pp-setup__alert--warn" role="alert">
                    {orphans.length} saved setting{orphans.length === 1 ? "" : "s"} no longer match the allowlist.
                    {" "}
                    <button type="button" className="pp-setup__alert-action" onClick={() => navigateToSettings("advanced", "local-storage-inspector")}>
                        Review →
                    </button>
                </div>
            )}

            {/* ── Step 1 · BI ───────────────────────────────────────── */}
            <FieldCard
                step={1}
                title="BI surface"
                subtitle="The dashboard, report, or canvas users will look at."
                status={{ tone: biStatus, label: biStatus === "ok" ? "Configured" : biStatus === "warn" ? "Needs embed" : "Not picked" }}
                tip={{
                    title: "PulsePlay hosts the BI surface",
                    body: [
                        "Pick the vendor your team already uses.",
                        "Paste the embed URL once configured.",
                        ...(allowlist?.biProviders?.length
                            ? [`Allowlist permits: ${allowlist.biProviders.join(", ")}.`]
                            : []),
                    ],
                }}
            >
                <FieldRow
                    label="Surface mode"
                    required
                    hint="Auto uses your vendor when it is configured, otherwise native renders AI results. Force either mode when a deployment needs it."
                    tip={{
                        title: "Runtime surface",
                        body: [
                            "Auto is the default for packs and local recon.",
                            "Vendor is for a real embedded dashboard.",
                            "Native is the renderer-only Databricks-first result canvas.",
                        ],
                    }}
                >
                    <BiSurfaceModeSegmentedControl value={biSurfaceMode} onChange={setBiSurfaceMode} />
                    <p style={{ margin: "6px 0 0", fontSize: 11, opacity: 0.66 }}>
                        Runtime: <code>{runtimeBiVendor}</code>
                        {surfaceResolution.reason === "auto-no-vendor-config" ? " (native fallback until embed config exists)" : ""}.
                    </p>
                </FieldRow>

                <FieldRow
                    label="Provider"
                    required={biSurfaceMode !== "native"}
                    hint={biSurfaceMode === "native"
                        ? "Optional vendor intent kept for later. Native mode still renders in the BI pane now."
                        : "The vendor PulsePlay embeds when the runtime surface is vendor-backed."}
                    tip={biVendor ? VENDOR_HELP[biVendor] : "Pick a provider to see its specific embed requirements."}
                >
                    <select
                        id="pp-setup-vendor"
                        value={biVendor}
                        onChange={e => setBiVendor(e.target.value)}
                        disabled={allowlistLoading}
                    >
                        <option value="">— Pick a dashboard tool —</option>
                        {allowedBiVendors.map(v => (
                            <option key={v.vendor} value={v.vendor}>
                                {v.displayName}
                            </option>
                        ))}
                    </select>
                </FieldRow>

                {runtimeNativeBi && (
                    <div
                        role="note"
                        style={{
                            fontSize: 12,
                            lineHeight: 1.5,
                            padding: "10px 12px",
                            border: "1px solid var(--pp-border, rgba(0,0,0,0.12))",
                            borderRadius: 6,
                            background: "rgba(14, 165, 233, 0.06)",
                            color: "var(--pp-text, #0f172a)",
                        }}
                    >
                        Native is ready immediately. Ask Pulse can use this pane as the place to show generated result views. Vendor settings below are preserved for when you switch back to Vendor or Auto.
                    </div>
                )}

                {biVendor && !authorNativeBi && (
                    <FieldRow
                        label="Embed URL or iframe HTML"
                        hint="Paste the full embed URL (Power BI / Tableau / generic) OR the iframe HTML from Databricks Genie Share → Embed."
                        tip={{
                            title: "Use the full form for complex flows",
                            body: [
                                "Power BI SSO, backend service principal, or per-tile picking → BI → Embed.",
                                "This inline field handles single URL or paste-in iframe (the 80% case).",
                            ],
                        }}
                        error={embedError}
                        success={embedSavedAt ? "Embed config saved — switch to the app to see the canvas refresh." : null}
                    >
                        <textarea
                            id="pp-setup-embed"
                            value={embedUrl}
                            onChange={e => { setEmbedUrl(e.target.value); setEmbedError(null); }}
                            placeholder={biVendor === "databricks-genie"
                                ? '<iframe src="https://….databricks.com/embed/…" …></iframe>'
                                : "https://app.powerbi.com/reportEmbed?reportId=…"}
                            rows={3}
                            spellCheck={false}
                            style={{ fontFamily: "var(--pp-font-mono)", fontSize: 12 }}
                        />
                    </FieldRow>
                )}

                {biVendor && !authorNativeBi && (
                    <div className="pp-setup__row-actions">
                        <button type="button" className="pp-setup__primary" onClick={handleApplyEmbed} disabled={!embedUrl.trim()}>
                            Apply embed
                        </button>
                        {readiness.hasEmbedConfig && (
                            <button type="button" className="pp-setup__ghost" onClick={handleClearEmbed}>
                                Clear
                            </button>
                        )}
                        <button type="button" className="pp-setup__link" onClick={() => navigateToSettings("bi", "embed")}>
                            Open full embed settings
                        </button>
                    </div>
                )}
            </FieldCard>

            {/* ── Step 2 · AI ───────────────────────────────────────── */}
            <FieldCard
                step={2}
                title="AI assistant"
                subtitle="One assistant powers both AI Insights and Ask Pulse — pick its profile here."
                status={{ tone: aiStatus, label: aiStatus === "ok" ? "Configured" : "Not picked" }}
                tip={{
                    title: "PulsePlay orchestrates AI",
                    body: [
                        "It doesn't run the model — the proxy does.",
                        "Pick a profile the proxy knows: Genie, Foundation Model, Supervisor, Azure OpenAI, etc.",
                        ...(allowlist?.aiProfiles?.length
                            ? [`Approved profiles: ${allowlist.aiProfiles.join(", ")}.`]
                            : []),
                    ],
                }}
                actions={
                    <TestButton
                        label="Test proxy"
                        onTest={probeProxy}
                    />
                }
            >
                <FieldRow
                    label="AI profile"
                    labelTrailing={
                        activeProfileDocs && (
                            // Docs link rendered next to the label — outside the
                            // tooltip per Codex 2026-05-19 tooltip audit P1-2.
                            // ARIA tooltips can't host interactive controls; this
                            // link is a sibling so it's keyboard-reachable,
                            // screen-reader announced as a real link, and not
                            // buried inside a pointer-events:none container.
                            <a
                                href={activeProfileDocs.href}
                                target="_blank"
                                rel="noreferrer"
                                style={{ fontSize: 11, fontWeight: 500, marginLeft: 4, color: "var(--pp-accent)", display: "inline-flex", alignItems: "center", gap: 3 }}
                            >
                                {activeProfileDocs.label}
                                {/* External-link SVG glyph replaces the U+2197 "↗"
                                  * character so accessible name + text snapshots
                                  * stay clean. Codex naming audit fix. */}
                                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                                    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                                    <polyline points="15 3 21 3 21 9" />
                                    <line x1="10" y1="14" x2="21" y2="3" />
                                </svg>
                            </a>
                        )
                    }
                    required
                    hint={
                        // Codex 2026-05-19 tooltip audit P1-3: when the proxy
                        // is online but the select is empty, the original
                        // tooltip was conceptual and didn't explain the
                        // blocked state. Inline hint now names the most
                        // common reasons so authors can self-diagnose.
                        allowlistLoading
                            ? "Loading available profiles from the proxy allowlist…"
                            : visibleProfiles.length === 0
                                ? "No profiles available. Either the proxy /assistant/profiles call failed, or all profiles are blocked by the configured allowlist. Check Settings → System → Proxy status to confirm."
                                : "Maps to a profile in proxy/config.json. The proxy holds all credentials — your browser never sees a token."
                    }
                    // Codex 2026-05-19 tooltip audit P1-2 fix: removed the
                    // <a href> from inside the tooltip body. ARIA tooltips
                    // are non-interactive (pointer-events:none); links
                    // inside them can't be clicked reliably. The docs link
                    // is rendered as a separate sibling below the select.
                    tip={{
                        title: "A profile is a named backend",
                        body: [
                            "The proxy knows how to call each one.",
                            "Common types: genie, foundation-stream, supervisor, azure-openai, bedrock.",
                        ],
                    }}
                >
                    <select
                        id="pp-setup-ai-profile"
                        value={activeAiProfile}
                        onChange={e => setActiveAiProfile(e.target.value)}
                        disabled={allowlistLoading || profilesLoading || visibleProfiles.length === 0}
                    >
                        <option value="">— Pick an AI profile —</option>
                        {visibleProfiles.map(p => (
                            <option key={p.name} value={p.name}>{p.displayName || p.name}</option>
                        ))}
                    </select>
                </FieldRow>

                <div className="pp-setup__row-actions">
                    <TestButton label="Test selected profile" onTest={probeAiProfile} disabled={!activeAiProfile} disabledHint="Pick a profile first" />
                    <button type="button" className="pp-setup__link" onClick={() => navigateToSettings("ai", "ai-insights")}>
                        Tune Insights behavior
                    </button>
                </div>
            </FieldCard>

            {/* ── Step 3 · Domain knowledge ─────────────────────────── */}
            <FieldCard
                step={3}
                title="Domain knowledge"
                subtitle="Industry vocabulary the assistant uses to interpret your data."
                status={{ tone: packStatus, label: packSelection ? "Selected" : "Optional" }}
                tip={{
                    title: "A pack is your industry's vocabulary",
                    body: [
                        "Bundles domain terms, metric definitions, guidance prompts.",
                        "Without one: generic vocabulary. With one: CPG, retail, finance, etc.",
                        ...(allowlist?.packs?.length
                            ? [`Allowlist permits: ${allowlist.packs.join(", ")}.`]
                            : []),
                    ],
                }}
            >
                <FieldRow
                    label="Pack"
                    hint="Optional but recommended. Picks vocab + metric direction rules tuned for the industry."
                    tip={<>You can <strong>browse pack content</strong> at <code>/knowledge/{packSelection?.pack ?? '<pack>'}</code> after selecting.</>}
                >
                    <select
                        id="pp-setup-pack"
                        value={packSelection?.pack ?? ""}
                        onChange={e => setPackSelection(e.target.value ? { pack: e.target.value } : null)}
                        disabled={allowlistLoading || packsLoading || visiblePacks.length === 0}
                    >
                        <option value="">— No pack (generic vocabulary) —</option>
                        {visiblePacks.map(p => (
                            <option key={p.name} value={p.name}>{p.displayName || p.name}</option>
                        ))}
                    </select>
                </FieldRow>

                {packSelection?.pack && (
                    <div className="pp-setup__row-actions">
                        <a
                            className="pp-setup__link"
                            href={`/knowledge/${encodeURIComponent(packSelection.pack)}`}
                            target="_blank"
                            rel="noreferrer"
                            style={{ display: "inline-flex", alignItems: "center", gap: 4 }}
                        >
                            Browse pack content
                            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                                <polyline points="15 3 21 3 21 9" />
                                <line x1="10" y1="14" x2="21" y2="3" />
                            </svg>
                        </a>
                    </div>
                )}
            </FieldCard>

            {/* ── Footer · jump to peer groups ────────────────────────
              * Audit 2026-05-19: was "Continue setup", implying these are
              * required next steps. They're optional cross-links into other
              * groups — Layout in Preferences, Proxy in System, etc. Renamed
              * to "Related areas" so users know they're done with Setup once
              * the cards above are green. */}
            <div className="pp-setup__footer">
                <p className="pp-setup__footer-label">Related areas</p>
                <div className="pp-setup__footer-links">
                    <FooterLink label="Layout & display" group="preferences" />
                    <FooterLink label="Proxy & diagnostics" group="system" />
                    <FooterLink label="Advanced / reset" group="advanced" />
                </div>
            </div>
        </section>
    );
}

function BiSurfaceModeSegmentedControl(props: {
    value: BiSurfaceMode;
    onChange: (value: BiSurfaceMode) => void;
}): React.ReactElement {
    const options: Array<{ value: BiSurfaceMode; label: string; title: string }> = [
        { value: "auto", label: "Auto", title: "Vendor when configured, otherwise native" },
        { value: "vendor", label: "Vendor", title: "Force the selected vendor adapter" },
        { value: "native", label: "Native", title: "Force PulsePlay's native result renderer" },
    ];
    return (
        <div role="group" aria-label="BI surface mode" style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
            {options.map(option => {
                const selected = props.value === option.value;
                return (
                    <button
                        key={option.value}
                        type="button"
                        aria-pressed={selected}
                        title={option.title}
                        onClick={() => props.onChange(option.value)}
                        style={{
                            border: `1px solid ${selected ? "var(--pp-accent, #0078d4)" : "var(--pp-border, rgba(0,0,0,0.18))"}`,
                            background: selected ? "rgba(0,120,212,0.08)" : "transparent",
                            color: "var(--pp-text, #1d1d1f)",
                            borderRadius: 5,
                            cursor: "pointer",
                            fontSize: 12,
                            fontWeight: selected ? 700 : 500,
                            minWidth: 76,
                            padding: "6px 10px",
                        }}
                    >
                        {option.label}
                    </button>
                );
            })}
        </div>
    );
}

function FooterLink(props: { label: string; group: "bi" | "ai" | "preferences" | "system" | "advanced" }): React.ReactElement {
    return (
        <button type="button" className="pp-setup__footer-link" onClick={() => navigateToSettings(props.group)}>
            {props.label}
        </button>
    );
}

function normalizeProfilesPayload(data: unknown): SetupProfileMetadata[] {
    const list = Array.isArray(data)
        ? data
        : Array.isArray((data as { profiles?: unknown } | null)?.profiles)
            ? (data as { profiles: unknown[] }).profiles
            : [];
    return list
        .filter((p): p is Record<string, unknown> => !!p && typeof p === "object" && typeof p.name === "string" && p.name.trim().length > 0)
        .map(p => ({
            name: String(p.name),
            displayName: typeof p.displayName === "string" ? p.displayName : undefined,
            dataDomain: typeof p.dataDomain === "string" ? p.dataDomain : undefined,
            description: typeof p.description === "string" ? p.description : undefined,
            spaceId: typeof p.spaceId === "string" ? p.spaceId : undefined,
            type: typeof p.type === "string" ? p.type : undefined,
            spaces: Array.isArray(p.spaces) ? p.spaces.filter((s): s is string => typeof s === "string") : undefined,
        }));
}

function normalizePacksPayload(data: unknown): SetupPackOption[] {
    const list = Array.isArray(data)
        ? data
        : Array.isArray((data as { packs?: unknown } | null)?.packs)
            ? (data as { packs: unknown[] }).packs
            : [];
    return list
        .filter((p): p is Record<string, unknown> => !!p && typeof p === "object" && typeof p.name === "string" && p.name.trim().length > 0)
        .map(p => ({
            name: String(p.name),
            displayName: typeof p.displayName === "string" ? p.displayName : undefined,
        }));
}

function docsForProfile(profile: SetupProfileMetadata | null, selectedName: string): { href: string; label: string } | null {
    if (!selectedName) return null;
    const type = profile?.type || "";
    if (type === "foundation-model") {
        return {
            href: "https://docs.databricks.com/en/machine-learning/foundation-models/index.html",
            label: "Foundation Model docs",
        };
    }
    if (type === "supervisor" || type === "supervisor-local" || type === "responses-agent") {
        return {
            href: "https://docs.databricks.com/aws/en/generative-ai/agent-framework/create-agent",
            label: "Agent Framework docs",
        };
    }
    if (type === "powerbi-semantic-model") {
        return {
            href: "https://learn.microsoft.com/power-bi/developer/embedded/",
            label: "Power BI docs",
        };
    }
    if (profile?.spaceId || !type) {
        return {
            href: "https://docs.databricks.com/aws/genie/",
            label: "Genie docs",
        };
    }
    return {
        href: "https://docs.databricks.com/",
        label: "Connector docs",
    };
}

// ── Helpers ────────────────────────────────────────────────────────

/** Best-effort read of the primary URL out of an existing embed config so
 *  the textarea pre-fills when the author re-opens Setup. */
function readEmbedUrl(cfg: unknown): string {
    if (!cfg || typeof cfg !== "object") return "";
    const c = cfg as Record<string, unknown>;
    if (typeof c.url === "string") return c.url;
    if (typeof c.embedUrl === "string") return c.embedUrl;
    if (typeof c.iframeHtml === "string") return c.iframeHtml;
    if (typeof c.dashboardUrl === "string") return c.dashboardUrl;
    return "";
}

/** Build a minimal BIEmbedConfig from a single URL / iframe string. Returns
 *  null when the vendor needs a multi-field form (Power BI SSO, etc.). */
function buildEmbedConfig(vendor: string, raw: string): Record<string, unknown> | null {
    const v = raw.trim();
    if (vendor === "databricks-genie") {
        // Genie accepts the full iframe HTML or just the src URL.
        return { vendor, iframeHtml: v };
    }
    if (vendor === "generic-iframe" || vendor === "tableau" || vendor === "qlik" || vendor === "looker") {
        return { vendor, url: v };
    }
    if (vendor === "databricks-aibi") {
        return { vendor, mode: "basic", url: v };
    }
    if (vendor === "powerbi") {
        // Power BI secure-embed link or raw embed URL — the BI page has the
        // proper extractor; here we just stash the URL and let the SDK fail
        // gracefully if the format isn't recognised, which is honest.
        return { vendor, mode: "secure", secureLink: v };
    }
    return null;
}
