// playground/src/settings/groups/SetupGroup.tsx
//
// Quick Setup — single-page canvas that gets PulsePlay 80% configured
// without the author having to navigate between BI, AI, Preferences,
// System, and Advanced. Inline pickers + live test buttons + rich help
// tooltips. The deeper per-area pages remain available for fine-tuning.

import { useCallback, useMemo, useState } from "react";
import { navigateToSettings } from "../settingsRoute";
import { useSettings } from "../settingsStore";
import { useEmbedConfig } from "../embedConfigStore";
import { getSetupReadiness } from "../setupReadiness";
import { listVendors } from "../../biPanel/registry";
import {
    FieldCard,
    FieldRow,
    StatusBadge,
    TestButton,
    type TestResult,
} from "../primitives";
import "../primitives/primitives.css";

const VENDOR_HELP: Record<string, React.ReactNode> = {
    "powerbi": (
        <>
            <strong>Microsoft Power BI.</strong> Embed reports via the official <code>powerbi-client</code> SDK. Requires an embed URL, workspace ID, and report ID. Authentication can be SSO (AAD), service principal, or a paste-in secure embed link.
        </>
    ),
    "databricks-aibi": (
        <>
            <strong>Databricks AI/BI dashboards.</strong> Embed via the <code>@databricks/aibi-client</code> token flow or a basic iframe. SDK mode needs a workspace URL, dashboard ID, and workspace ID; basic mode just needs an embed URL.
        </>
    ),
    "databricks-genie": (
        <>
            <strong>Databricks Genie Space.</strong> Paste the iframe HTML generated by <em>Share → Embed space</em> in the Genie UI. No SDK needed.
        </>
    ),
    "tableau": <><strong>Tableau.</strong> View URL via Tableau Embedding API v3. Bring the public/server view URL.</>,
    "qlik": <><strong>Qlik Sense.</strong> Apps/sheets via qlik-embed web components or the Single Integration iframe API.</>,
    "looker": <><strong>Looker.</strong> Dashboards / Looks via signed-URL iframe + JS embed events.</>,
    "generic-iframe": <><strong>Generic iframe.</strong> Any URL — escape hatch for vendors PulsePlay doesn't yet have an SDK adapter for. Works today; no credentials needed.</>,
};

export function SetupGroup(): React.ReactElement {
    const {
        biVendor, activeAiProfile, packSelection,
        allowlist, allowlistError, allowlistLoading, orphans,
        setBiVendor, setActiveAiProfile, setPackSelection,
    } = useSettings();
    const { embedConfig, setEmbedConfig } = useEmbedConfig();
    const readiness = getSetupReadiness({ biVendor, embedConfig, activeAiProfile });

    const vendors = useMemo(() => listVendors(), []);
    const allowedBiVendors = useMemo(() => {
        if (!allowlist?.biProviders?.length) return vendors;
        const set = new Set(allowlist.biProviders);
        return vendors.filter(v => set.has(v.vendor));
    }, [vendors, allowlist]);

    const aiProfiles = allowlist?.aiProfiles ?? [];
    const packs = allowlist?.packs ?? [];

    // ── Live probe handlers ────────────────────────────────────────
    const probeProxy = useCallback<() => Promise<TestResult>>(async () => {
        const started = performance.now();
        try {
            const res = await fetch("/api/health", { headers: { Accept: "application/json" } });
            const elapsed = Math.round(performance.now() - started);
            if (!res.ok) {
                return { tone: "missing", label: "Proxy unreachable", detail: `HTTP ${res.status} · ${elapsed} ms` };
            }
            const data = await res.json();
            const profileCount = Array.isArray(data?.profiles) ? data.profiles.length : 0;
            return {
                tone: "ok",
                label: "Proxy online",
                detail: `${profileCount} profile${profileCount === 1 ? "" : "s"} · ${elapsed} ms`,
            };
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return { tone: "missing", label: "Proxy offline", detail: msg.slice(0, 100) };
        }
    }, []);

    const probeAiProfile = useCallback<() => Promise<TestResult>>(async () => {
        if (!activeAiProfile) {
            return { tone: "warn", label: "No profile selected", detail: "Pick a profile above first" };
        }
        try {
            const res = await fetch(`/api/assistant/profiles?assistantProfile=${encodeURIComponent(activeAiProfile)}`, {
                headers: { Accept: "application/json" },
            });
            if (!res.ok) {
                return { tone: "missing", label: "Profile probe failed", detail: `HTTP ${res.status}` };
            }
            const data = await res.json();
            const profile = Array.isArray(data?.profiles)
                ? data.profiles.find((p: any) => p?.name === activeAiProfile)
                : null;
            if (!profile) {
                return { tone: "warn", label: "Profile not registered", detail: `'${activeAiProfile}' missing on proxy` };
            }
            const detail = profile.type ? `${profile.type}${profile.spaceId ? " · space " + profile.spaceId.slice(0, 8) + "…" : ""}` : "registered";
            return { tone: "ok", label: "Profile reachable", detail };
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return { tone: "missing", label: "Probe failed", detail: msg.slice(0, 100) };
        }
    }, [activeAiProfile]);

    // ── Inline embed URL editor (the most common config path) ──────
    const [embedUrl, setEmbedUrl] = useState<string>(() => readEmbedUrl(embedConfig));
    const [embedError, setEmbedError] = useState<string | null>(null);
    const [embedSavedAt, setEmbedSavedAt] = useState<number | null>(null);

    const handleApplyEmbed = useCallback(() => {
        setEmbedError(null);
        const url = embedUrl.trim();
        if (!url) {
            setEmbedError("Enter the embed URL or iframe HTML before applying.");
            return;
        }
        try {
            const cfg = buildEmbedConfig(biVendor, url);
            if (!cfg) {
                setEmbedError(`PulsePlay can't auto-build a config for '${biVendor}' from a single URL. Use the BI group → Embed for the full form.`);
                return;
            }
            setEmbedConfig(cfg);
            setEmbedSavedAt(Date.now());
        } catch (err) {
            setEmbedError(err instanceof Error ? err.message : String(err));
        }
    }, [biVendor, embedUrl, setEmbedConfig]);

    const handleClearEmbed = useCallback(() => {
        setEmbedConfig(null);
        setEmbedUrl("");
        setEmbedError(null);
        setEmbedSavedAt(null);
    }, [setEmbedConfig]);

    // ── Card status tones ──────────────────────────────────────────
    const biStatus = biVendor && readiness.hasEmbedConfig ? "ok" : !biVendor ? "missing" : "warn";
    const aiStatus = activeAiProfile ? "ok" : "missing";
    const packStatus = packSelection ? "ok" : "warn";

    return (
        <section aria-labelledby="settings-setup-title" className="pp-setup">
            <header className="pp-setup__head">
                <div>
                    <h2 id="settings-setup-title" className="pp-setup__title">
                        Setup
                    </h2>
                    <p className="pp-setup__subtitle">
                        Three short steps to get PulsePlay running. Each card configures one axis inline; deeper tuning lives in the BI, AI, and Preferences pages.
                    </p>
                </div>
                <div className="pp-setup__readiness">
                    <StatusBadge
                        tone={readiness.ready ? "ok" : "warn"}
                        label={readiness.ready ? "Ready" : "Setup needed"}
                        detail={readiness.ready ? "BI + AI" : `Missing: ${readiness.missing.join(", ")}`}
                    />
                </div>
            </header>

            {allowlistError && (
                <div className="pp-setup__alert" role="alert">
                    <strong>Governance allowlist unreachable.</strong> {allowlistError}
                    {" · "}
                    <button type="button" className="pp-setup__alert-action" onClick={() => navigateToSettings("system", "proxy-status")}>
                        Check proxy →
                    </button>
                </div>
            )}

            {orphans.length > 0 && (
                <div className="pp-setup__alert pp-setup__alert--warn" role="alert">
                    {orphans.length} saved setting{orphans.length === 1 ? "" : "s"} no longer match the allowlist.
                    {" "}
                    <button type="button" className="pp-setup__alert-action" onClick={() => navigateToSettings("advanced", "local-storage-inspector")}>
                        Review →
                    </button>
                </div>
            )}

            {/* ── Step 1 · BI ───────────────────────────────────────── */}
            <FieldCard
                step={1}
                title="BI tool"
                subtitle="The dashboard, report, or canvas users look at."
                status={{ tone: biStatus, label: biStatus === "ok" ? "Configured" : biStatus === "warn" ? "Needs embed" : "Not picked" }}
                tip={
                    <>
                        PulsePlay <strong>hosts</strong> the BI surface — it doesn't replace it. Pick the vendor your team already uses, then paste the embed URL.
                        {allowlist?.biProviders?.length ? (
                            <> Your governance allowlist permits: <code>{allowlist.biProviders.join(", ")}</code>.</>
                        ) : null}
                    </>
                }
            >
                <FieldRow
                    label="Provider"
                    required
                    hint="The BI vendor PulsePlay will embed in the canvas pane."
                    tip={biVendor ? VENDOR_HELP[biVendor] : "Pick a provider to see its specific embed requirements."}
                >
                    <select
                        id="pp-setup-vendor"
                        value={biVendor}
                        onChange={e => setBiVendor(e.target.value)}
                        disabled={allowlistLoading}
                    >
                        <option value="">— Pick a BI tool —</option>
                        {allowedBiVendors.map(v => (
                            <option key={v.vendor} value={v.vendor}>
                                {v.displayName}
                            </option>
                        ))}
                    </select>
                </FieldRow>

                {biVendor && (
                    <FieldRow
                        label="Embed URL or iframe HTML"
                        hint="Paste the full embed URL (Power BI / Tableau / generic) OR the iframe HTML from Databricks Genie Share → Embed."
                        tip={
                            <>
                                For complex flows like Power BI <strong>SSO</strong>, <strong>backend service principal</strong>, or per-tile picking — use the full form on the <em>BI → Embed</em> page. This inline field handles the 80% case of a single URL or paste-in iframe.
                            </>
                        }
                        error={embedError}
                        success={embedSavedAt ? "Embed config saved — switch to the app to see the canvas refresh." : null}
                    >
                        <textarea
                            id="pp-setup-embed"
                            value={embedUrl}
                            onChange={e => { setEmbedUrl(e.target.value); setEmbedError(null); }}
                            placeholder={biVendor === "databricks-genie"
                                ? '<iframe src="https://….databricks.com/embed/…" …></iframe>'
                                : "https://app.powerbi.com/reportEmbed?reportId=…"}
                            rows={3}
                            spellCheck={false}
                            style={{ fontFamily: "var(--pp-font-mono)", fontSize: 12 }}
                        />
                    </FieldRow>
                )}

                {biVendor && (
                    <div className="pp-setup__row-actions">
                        <button type="button" className="pp-setup__primary" onClick={handleApplyEmbed} disabled={!embedUrl.trim()}>
                            Apply embed
                        </button>
                        {readiness.hasEmbedConfig && (
                            <button type="button" className="pp-setup__ghost" onClick={handleClearEmbed}>
                                Clear
                            </button>
                        )}
                        <button type="button" className="pp-setup__link" onClick={() => navigateToSettings("bi", "embed")}>
                            Full embed form →
                        </button>
                    </div>
                )}
            </FieldCard>

            {/* ── Step 2 · AI ───────────────────────────────────────── */}
            <FieldCard
                step={2}
                title="AI brain"
                subtitle="The assistant powering AI Insights and Ask Pulse."
                status={{ tone: aiStatus, label: aiStatus === "ok" ? "Configured" : "Not picked" }}
                tip={
                    <>
                        PulsePlay <strong>orchestrates</strong> AI — it doesn't run the model. Pick a profile your proxy already knows about (Genie, Foundation Model, Supervisor, Azure OpenAI, etc.).
                        {allowlist?.aiProfiles?.length ? (
                            <> Approved profiles: <code>{allowlist.aiProfiles.join(", ")}</code>.</>
                        ) : null}
                    </>
                }
                actions={
                    <TestButton
                        label="Test proxy"
                        onTest={probeProxy}
                    />
                }
            >
                <FieldRow
                    label="AI profile"
                    required
                    hint="Maps to a profile in proxy/config.json. The proxy holds all credentials — your browser never sees a token."
                    tip={
                        <>
                            A <strong>profile</strong> is a named backend the proxy knows how to call. Common types: <code>genie</code>, <code>foundation-stream</code>, <code>supervisor</code>, <code>azure-openai</code>, <code>bedrock</code>.
                            {" "}<a href="https://docs.databricks.com" target="_blank" rel="noreferrer">Databricks docs ↗</a>
                        </>
                    }
                >
                    <select
                        id="pp-setup-ai-profile"
                        value={activeAiProfile}
                        onChange={e => setActiveAiProfile(e.target.value)}
                        disabled={allowlistLoading || aiProfiles.length === 0}
                    >
                        <option value="">— Pick an AI profile —</option>
                        {aiProfiles.map(p => (
                            <option key={p} value={p}>{p}</option>
                        ))}
                    </select>
                </FieldRow>

                <div className="pp-setup__row-actions">
                    <TestButton label="Test selected profile" onTest={probeAiProfile} disabled={!activeAiProfile} disabledHint="Pick a profile first" />
                    <button type="button" className="pp-setup__link" onClick={() => navigateToSettings("ai", "ai-insights")}>
                        Tune Insights behavior →
                    </button>
                </div>
            </FieldCard>

            {/* ── Step 3 · Knowledge pack ───────────────────────────── */}
            <FieldCard
                step={3}
                title="Knowledge pack"
                subtitle="Domain vocabulary the assistant uses to interpret your data."
                status={{ tone: packStatus, label: packSelection ? "Selected" : "Optional" }}
                tip={
                    <>
                        A pack is a bundle of domain terms, metric definitions, and guidance prompts. Without a pack the assistant uses generic vocabulary; with one it speaks your industry's language (CPG, retail, finance, etc.).
                        {allowlist?.packs?.length ? (
                            <> Allowlist permits: <code>{allowlist.packs.join(", ")}</code>.</>
                        ) : null}
                    </>
                }
            >
                <FieldRow
                    label="Pack"
                    hint="Optional but recommended. Picks vocab + metric direction rules tuned for the industry."
                    tip={<>You can <strong>browse pack content</strong> at <code>/knowledge/{packSelection?.pack ?? '<pack>'}</code> after selecting.</>}
                >
                    <select
                        id="pp-setup-pack"
                        value={packSelection?.pack ?? ""}
                        onChange={e => setPackSelection(e.target.value ? { pack: e.target.value } : null)}
                        disabled={allowlistLoading || packs.length === 0}
                    >
                        <option value="">— No pack (generic vocabulary) —</option>
                        {packs.map(p => (
                            <option key={p} value={p}>{p}</option>
                        ))}
                    </select>
                </FieldRow>

                {packSelection?.pack && (
                    <div className="pp-setup__row-actions">
                        <a
                            className="pp-setup__link"
                            href={`/knowledge/${encodeURIComponent(packSelection.pack)}`}
                            target="_blank"
                            rel="noreferrer"
                        >
                            Browse pack content ↗
                        </a>
                    </div>
                )}
            </FieldCard>

            {/* ── Footer · jump to advanced groups ──────────────────── */}
            <div className="pp-setup__footer">
                <p className="pp-setup__footer-label">Fine-tune further</p>
                <div className="pp-setup__footer-links">
                    <FooterLink label="Layout & display" group="preferences" />
                    <FooterLink label="Proxy & diagnostics" group="system" />
                    <FooterLink label="Advanced / reset" group="advanced" />
                </div>
            </div>
        </section>
    );
}

function FooterLink(props: { label: string; group: "bi" | "ai" | "preferences" | "system" | "advanced" }): React.ReactElement {
    return (
        <button type="button" className="pp-setup__footer-link" onClick={() => navigateToSettings(props.group)}>
            {props.label} →
        </button>
    );
}

// ── Helpers ────────────────────────────────────────────────────────

/** Best-effort read of the primary URL out of an existing embed config so
 *  the textarea pre-fills when the author re-opens Setup. */
function readEmbedUrl(cfg: unknown): string {
    if (!cfg || typeof cfg !== "object") return "";
    const c = cfg as Record<string, unknown>;
    if (typeof c.url === "string") return c.url;
    if (typeof c.embedUrl === "string") return c.embedUrl;
    if (typeof c.iframeHtml === "string") return c.iframeHtml;
    if (typeof c.dashboardUrl === "string") return c.dashboardUrl;
    return "";
}

/** Build a minimal BIEmbedConfig from a single URL / iframe string. Returns
 *  null when the vendor needs a multi-field form (Power BI SSO, etc.). */
function buildEmbedConfig(vendor: string, raw: string): Record<string, unknown> | null {
    const v = raw.trim();
    if (vendor === "databricks-genie") {
        // Genie accepts the full iframe HTML or just the src URL.
        return { vendor, iframeHtml: v };
    }
    if (vendor === "generic-iframe" || vendor === "tableau" || vendor === "qlik" || vendor === "looker") {
        return { vendor, url: v };
    }
    if (vendor === "databricks-aibi") {
        return { vendor, mode: "basic", url: v };
    }
    if (vendor === "powerbi") {
        // Power BI secure-embed link or raw embed URL — the BI page has the
        // proper extractor; here we just stash the URL and let the SDK fail
        // gracefully if the format isn't recognised, which is honest.
        return { vendor, mode: "secure", secureLink: v };
    }
    return null;
}
