#!/usr/bin/env python3
"""
4-iteration deep adversarial question battery.
Focus: accuracy, completeness, performance, worst-case identity/schema confusion,
composite+fusion questions across sales + hse spaces.

Each iteration escalates complexity and adversarialism.
"""
import json, time, urllib.request, threading, queue, sys

BASE = "http://127.0.0.1:8787"
MAX_WAIT = 200  # seconds per question

def post(path, payload):
    req = urllib.request.Request(BASE + path,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r: return json.loads(r.read())

def get(path):
    with urllib.request.urlopen(BASE + path, timeout=30) as r: return json.loads(r.read())

def extract(poll):
    for att in poll.get("attachments", []):
        t = att.get("text")
        if isinstance(t, str) and t.strip(): return t
        if isinstance(t, dict) and t.get("content"): return str(t["content"])
    return str(poll.get("content", "(no answer)"))

def is_clarify(a):
    l = a.lower().strip()
    return (l.startswith("would you") or l.startswith("could you") or
            l.startswith("do you want") or l.startswith("please clarify") or
            (l.endswith("?") and len(a) < 180))

def ask(profile, question):
    t0 = time.time()
    try:
        s = post("/assistant/conversations/start", {"assistantProfile": profile, "content": question, "contextText": ""})
        conv = s.get("conversation_id"); msg = s.get("message_id")
        if not conv: return None, "NO_CONV", "(no conversationId)", 0
        status = "SUBMITTED"; poll = {}
        while time.time() - t0 < MAX_WAIT:
            time.sleep(4)
            try: poll = get(f"/assistant/conversations/{conv}/messages/{msg}?assistantProfile={profile}")
            except: continue
            status = poll.get("status", "")
            if status in ("COMPLETED","FAILED","CANCELLED"): break
        elapsed = round(time.time()-t0, 1)
        answer = extract(poll)
        return elapsed, status, answer, len(answer)
    except Exception as e:
        return None, "ERROR", str(e), 0

def ask_parallel(questions):
    """Fire questions simultaneously, return results in order."""
    result_q = queue.Queue()
    def worker(idx, profile, q):
        elapsed, status, answer, alen = ask(profile, q)
        result_q.put((idx, profile, q, elapsed, status, answer, alen))
    threads = []
    for i, (profile, q) in enumerate(questions):
        t = threading.Thread(target=worker, args=(i, profile, q))
        threads.append(t); t.start(); time.sleep(0.3)
    for t in threads: t.join(timeout=220)
    results = []
    while not result_q.empty(): results.append(result_q.get())
    return sorted(results, key=lambda x: x[0])

def print_q(label, profile, q, elapsed, status, answer, alen):
    flag = "[CLARIFY]" if is_clarify(answer) else ("[ERR]" if status != "COMPLETED" else "[OK]")
    print(f"\n  {flag} {label} [{profile}] {elapsed}s | {alen} chars")
    print(f"  Q: {q[:120]}{'...' if len(q)>120 else ''}")
    print(f"  A: {answer[:600]}{'...' if len(answer)>600 else ''}")

# ═══════════════════════════════════════════════════════════════════
# ITERATION 1: Composite — multi-part questions, identity traps,
# ambiguous metric names, wrong-sounding but valid questions
# ═══════════════════════════════════════════════════════════════════
ITER1 = [
    # Composite: 3 metrics, 2 dimensions, explicit ranking
    ("sales",
     "For the West region only: (1) total sales and profit, (2) the top 3 sub-categories by sales, "
     "(3) which customer segment has the highest return rate. Do not ask clarifying questions — use all available data."),

    # Identity trap: 'revenue' ≠ 'sales' — does Genie map it correctly?
    ("sales",
     "What is the total revenue generated by Corporate customers in the Technology category in 2017? "
     "Also state the total number of invoices raised for this segment and category."),

    # Wrong schema — 'invoice date' not a column; Genie should handle gracefully
    ("sales",
     "Show me the top 5 months by invoice date with the highest sales volume. "
     "If invoice date is not available, use order date instead and clearly state what you used."),

    # Mistaken identity: 'profit margin' — is it profit/sales or profit/cost?
    ("sales",
     "Calculate profit margin for each region. Define profit margin as profit divided by sales. "
     "Flag any region where profit margin is below 10%."),

    # Cross-space composite (HSE targets)
    ("hse",
     "For 2017: list all months where the Central region missed its sales target by more than 20%. "
     "For each missed month, state the actual sales, the target, and the shortfall amount."),
]

# ═══════════════════════════════════════════════════════════════════
# ITERATION 2: Fusion simulation — same question to both spaces,
# parallel fire, compare accuracy of Sales vs HSE answers
# ═══════════════════════════════════════════════════════════════════
ITER2_SALES = [
    "What is the total profit for the West region in 2017?",
    "Which customer segment had the highest number of returned orders?",
    "What are the top 3 product categories by total sales?",
]
ITER2_HSE = [
    "What is the total actual sales for the West region in 2017?",
    "Which product category appears most frequently in the HSE data?",
    "What is the average monthly target for the West region across all years?",
]

# ═══════════════════════════════════════════════════════════════════
# ITERATION 3: Ultra-complex adversarial + worst-case scenarios
# ═══════════════════════════════════════════════════════════════════
ITER3 = [
    # Worst-case: ambiguous year reference, multi-metric, ranking + threshold
    ("sales",
     "In the most recent year available in the dataset: identify all sub-categories where "
     "profit declined versus the prior year AND discount rate increased. "
     "For each such sub-category, quantify: (a) profit change in dollars, "
     "(b) discount rate change in percentage points, "
     "(c) whether the sub-category was also in the bottom quartile for sales volume. "
     "Do not ask clarifying questions."),

    # Worst-case: ambiguous customer identity — 'top customer' by what metric?
    ("sales",
     "Who is the top customer in terms of net value to the business — defined as total profit "
     "minus estimated cost of returns (assume returned order profit is zeroed out). "
     "Show the top 5 by this metric with their total orders, total profit, estimated return cost, and net value."),

    # Composite + HSE: cross-metric, cross-year, conditional logic
    ("hse",
     "Compare 2016 vs 2017 target attainment for each region. "
     "For any region that improved attainment by more than 10 percentage points, "
     "calculate: (a) absolute improvement, (b) whether actual sales also grew year-over-year, "
     "(c) whether target itself was raised or lowered between years. Do not ask clarifying questions."),

    # Temporal confusion: rolling window + outlier detection
    ("sales",
     "For each calendar month (Jan–Dec), compute the 3-month rolling average of profit "
     "across all years combined. Identify the 2 months where actual monthly profit deviated "
     "most from this rolling average (both above and below). State the deviation amount."),

    # Mistaken identity: confusing 'orders' with 'order lines'
    ("sales",
     "How many unique orders contain at least one item from the Furniture category? "
     "Also, of those orders, what percentage also include an item from Technology? "
     "Note: count at the order level, not the line item level."),
]

# ═══════════════════════════════════════════════════════════════════
# ITERATION 4: Ultra-fusion — parallel fire to both spaces, then
# explicit synthesis request to see if answers are consistent
# ═══════════════════════════════════════════════════════════════════
ITER4_QUESTIONS = [
    # Q fired to sales space
    ("sales",
     "What are the total sales, total profit, and profit margin for each region in 2017? "
     "Show results sorted by profit margin descending. Do not ask clarifying questions."),

    # Same scope but via HSE targets space for cross-validation
    ("hse",
     "What are the total actual sales and target attainment rate for each region in 2017? "
     "Sort by attainment rate descending. Do not ask clarifying questions."),

    # Composite: fusion challenge — both spaces address the same business question
    ("sales",
     "Which regions are under-performing on both profit margin (below 12%) AND "
     "high discount rate (above 20%)? Provide exact figures. Do not ask clarifying questions."),

    ("hse",
     "Which regions missed their sales targets for more than 4 months in 2017? "
     "For each such region, state how many months were missed and the average attainment in those months."),

    # Final ultra-hard: forces Genie to reason about data quality and completeness
    ("sales",
     "Are there any customers who appear in the returns data but have zero recorded sales? "
     "If yes, list them with their return order IDs. "
     "If no, state explicitly that all returning customers have associated sales records. "
     "This is a data quality check — answer precisely with counts."),
]

ALL_RESULTS = []

def run_sequential(label, questions, iteration):
    print(f"\n{'#'*66}")
    print(f"  ITERATION {iteration}: {label}")
    print(f"{'#'*66}")
    for i, (profile, q) in enumerate(questions, 1):
        elapsed, status, answer, alen = ask(profile, q)
        print_q(f"Q{i}", profile, q, elapsed, status, answer, alen)
        ALL_RESULTS.append({"iter": iteration, "q": i, "profile": profile,
            "elapsed": elapsed, "status": status, "clarify": is_clarify(answer), "alen": alen})

def run_parallel(label, sales_qs, hse_qs, iteration):
    print(f"\n{'#'*66}")
    print(f"  ITERATION {iteration}: {label} (parallel: {len(sales_qs)+len(hse_qs)} questions simultaneously)")
    print(f"{'#'*66}")
    combined = [("sales", q) for q in sales_qs] + [("hse", q) for q in hse_qs]
    results = ask_parallel(combined)
    for idx, profile, q, elapsed, status, answer, alen in results:
        print_q(f"Q{idx+1}", profile, q, elapsed, status, answer, alen)
        ALL_RESULTS.append({"iter": iteration, "q": idx+1, "profile": profile,
            "elapsed": elapsed, "status": status, "clarify": is_clarify(answer), "alen": alen})

# ── Main ─────────────────────────────────────────────────────────
run_sequential("COMPOSITE + IDENTITY TRAPS", ITER1, 1)
run_parallel("FUSION SIMULATION (parallel sales+hse)", ITER2_SALES, ITER2_HSE, 2)
run_sequential("ULTRA-COMPLEX ADVERSARIAL", ITER3, 3)
run_parallel("ULTRA-FUSION CROSS-VALIDATION", ITER4_QUESTIONS[:3], ITER4_QUESTIONS[3:], 4)

# ── Summary ──────────────────────────────────────────────────────
print(f"\n{'='*66}")
print("  DEEP BATTERY SUMMARY")
print(f"{'='*66}")
total = len(ALL_RESULTS)
completed  = [r for r in ALL_RESULTS if r["status"] == "COMPLETED"]
clarifying = [r for r in ALL_RESULTS if r["clarify"]]
errors     = [r for r in ALL_RESULTS if r["status"] not in ("COMPLETED","FAILED","CANCELLED") or r["status"] in ("FAILED","CANCELLED")]
slow       = [r for r in ALL_RESULTS if r["elapsed"] and r["elapsed"] > 60]
empty      = [r for r in ALL_RESULTS if r["alen"] < 80]

print(f"  Total questions  : {total}")
print(f"  COMPLETED        : {len(completed)}/{total}")
print(f"  Clarifying (!)   : {len(clarifying)}")
print(f"  Errors/Failed    : {len(errors)}")
print(f"  Slow (>60s)      : {len(slow)}")
print(f"  Thin (<80 chars) : {len(empty)}")

avg_time = sum(r["elapsed"] or 0 for r in completed) / max(len(completed),1)
print(f"  Avg response time: {round(avg_time,1)}s")

if slow:
    print("\n  Slow questions:")
    for r in slow: print(f"    Iter {r['iter']} Q{r['q']} [{r['profile']}] {r['elapsed']}s")
if clarifying:
    print("\n  Clarifying instead of answering:")
    for r in clarifying: print(f"    Iter {r['iter']} Q{r['q']} [{r['profile']}]")
if empty:
    print("\n  Thin/empty answers:")
    for r in empty: print(f"    Iter {r['iter']} Q{r['q']} [{r['profile']}] ({r['alen']} chars)")
