// bi-adapters/databricks-genie/embedUrl.ts
//
// Pure Genie embed-URL builder, split out of the adapter so non-adapter
// callers (e.g. playground/src/lib/workbenchDescriptors.ts) can resolve a
// Genie embed URL WITHOUT statically importing the whole DatabricksGenieAdapter
// (which pulls in GenericIframeAdapter). Keeping this dependency-light lets Vite
// code-split the adapter as a lazy chunk (registry.loadAdapter) instead of
// hoisting it into the main bundle. (build-warning cleanup 2026-06-04)

import type { BIEmbedConfig } from "../../playground/src/biPanel/BIAdapter";
import { BI_ERR } from "../../playground/src/biPanel/BIAdapter";

export interface GenieConfig extends BIEmbedConfig {
    /** Full iframe code copied from Databricks Share > Embed space. */
    iframe?: string;
    /** Legacy Quick Setup field retained for existing localStorage configs. */
    iframeHtml?: string;
    /** Full iframe src URL. Preferred when available. */
    url?: string;
    /** Optional loose fallback used only when admins standardize an embed path. */
    workspaceUrl?: string;
    spaceId?: string;
    embedPath?: string;
    title?: string;
}

function extractIframeSrc(input: string): string {
    const srcMatch = input.match(/\bsrc\s*=\s*["']([^"']+)["']/i);
    return (srcMatch?.[1] || input).trim().replace(/&amp;/g, "&");
}

export function buildGenieEmbedUrl(cfg: GenieConfig): string {
    const direct = cfg.url || cfg.iframe || cfg.iframeHtml;
    if (typeof direct === "string" && direct.trim()) return extractIframeSrc(direct);
    if (cfg.workspaceUrl && cfg.spaceId && cfg.embedPath) {
        const base = cfg.workspaceUrl.replace(/\/+$/, "");
        const path = cfg.embedPath
            .replace("{spaceId}", encodeURIComponent(cfg.spaceId))
            .replace(/^\/?/, "/");
        return `${base}${path}`;
    }
    throw new Error(
        `${BI_ERR.EMBED_FAILED}: databricks-genie requires the iframe src/code generated by Databricks, or { workspaceUrl + spaceId + embedPath }.`,
    );
}
