// bi-adapters/databricks-genie/index.ts
//
// Databricks Genie Space iframe adapter. Databricks documents Genie Space
// embedding as author-generated iframe code from the Share dialog; PulsePlay
// therefore treats the iframe src as the primary contract instead of inventing
// a private URL scheme.

import { GenericIframeAdapter } from "../generic-iframe/index";
import type { BIEmbedConfig } from "../../playground/src/biPanel/BIAdapter";
import { BI_ERR } from "../../playground/src/biPanel/BIAdapter";

interface GenieConfig extends BIEmbedConfig {
    /** Full iframe code copied from Databricks Share > Embed space. */
    iframe?: string;
    /** Legacy Quick Setup field retained for existing localStorage configs. */
    iframeHtml?: string;
    /** Full iframe src URL. Preferred when available. */
    url?: string;
    /** Optional loose fallback used only when admins standardize an embed path. */
    workspaceUrl?: string;
    spaceId?: string;
    embedPath?: string;
    title?: string;
}

function extractIframeSrc(input: string): string {
    const srcMatch = input.match(/\bsrc\s*=\s*["']([^"']+)["']/i);
    return (srcMatch?.[1] || input).trim().replace(/&amp;/g, "&");
}

export function buildGenieEmbedUrl(cfg: GenieConfig): string {
    const direct = cfg.url || cfg.iframe || cfg.iframeHtml;
    if (typeof direct === "string" && direct.trim()) return extractIframeSrc(direct);
    if (cfg.workspaceUrl && cfg.spaceId && cfg.embedPath) {
        const base = cfg.workspaceUrl.replace(/\/+$/, "");
        const path = cfg.embedPath
            .replace("{spaceId}", encodeURIComponent(cfg.spaceId))
            .replace(/^\/?/, "/");
        return `${base}${path}`;
    }
    throw new Error(
        `${BI_ERR.EMBED_FAILED}: databricks-genie requires the iframe src/code generated by Databricks, or { workspaceUrl + spaceId + embedPath }.`,
    );
}

export class DatabricksGenieAdapter extends GenericIframeAdapter {
    readonly vendor = "databricks-genie";
    readonly displayName = "Databricks Genie";
    protected defaultSandbox = "allow-scripts allow-same-origin allow-forms allow-popups";

    async mount(containerEl: HTMLElement | null, embedConfig: BIEmbedConfig): Promise<void> {
        const cfg = embedConfig as GenieConfig;
        const resolvedUrl = buildGenieEmbedUrl(cfg);
        return super.mount(containerEl, {
            ...cfg,
            url: resolvedUrl,
            title: typeof cfg.title === "string" ? cfg.title : "Databricks Genie Space",
            allow: "clipboard-write",
        });
    }
}
